admins/urls.py
from django.urls import path
import admins.views as admins

app_name = 'admins'

urlpatterns = [
    path('', admins.index, name='index'),
    path('users/create/', admins.UserCreateView.as_view(), name='admin_users_create'),
    path('users/read/', admins.UserListView.as_view(), name='admin_users'),
    path('users/update/<int:pk>/', admins.UserUpdateView.as_view(), name='admin_users_update'),
    path('users/delete/<int:pk>/', admins.UserDeleteView.as_view(), name='admin_users_remove'),

    path('categories/create/', admins.category_create, name='category_create'),
    path('categories/read/', admins.categories, name='categories'),
    path('categories/update/<int:pk>/', admins.ProductCategoryUpdateView.as_view(), name='category_update'),
    path('categories/delete/<int:pk>/', admins.category_delete, name='category_delete'),

    path('products/create/category/<int:pk>/', admins.product_create, name='product_create'),
    path('products/read/category/<int:pk>/', admins.CategoryProductsReadView.as_view(), name='product'),
    path('products/read/<int:pk>/', admins.CategoryProductsReadView.as_view(), name='product_read'),
    path('products/update/<int:pk>/', admins.product_update, name='product_update'),
    path('products/delete/<int:pk>/', admins.product_delete, name='product_delete'),
    path('products/', admins.products, name='products'),
]

geekshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from products.views import IndexView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('products/', include('products.urls', namespace='products')),
    path('users/', include('users.urls', namespace='users')),
    path('baskets/', include('baskets.urls', namespace='baskets')),
    path('admins/', include('admins.urls', namespace='admins')),
    path('', include('social_django.urls', namespace='social')),
    path('users/verify/google/oauth2/complete/', include("social_django.urls", namespace="social")),
    path('orders/', include('orders.urls', namespace='orders')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

products/urls.py
from django.urls import path
from .views import products, product

app_name = 'products'

urlpatterns = [
    path('', products, name='index'),
    path('category/<int:pk>/', products, name='category'),
    path('product/<int:pk>/', product, name='detail'),
    path('category/<int:pk>/page/<int:page>/', products, name='page'),
]

users/urls.py
from django.urls import path, re_path

from users.views import UserLoginView, register, UserLogoutView, UserProfileView, verify
from django.contrib.auth.decorators import login_required

app_name = 'users'

urlpatterns = [
    path('login/', UserLoginView.as_view(), name='login'),
    path('register/', register, name='register'),
    path('profile/<int:pk>/', login_required(UserProfileView.as_view()), name='profile'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('verify/<str:email>/<str:activation_key>/', verify, name='verify'),
]

products/models.py
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField(max_length=64, unique=True)
    description = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=256)
    image = models.ImageField(upload_to='products_images', blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    price = models.DecimalField(max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(default=0)
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    is_active = models.BooleanField(verbose_name='активна', default=True)

    @staticmethod
    def get_items():
        return Product.objects.filter(is_active=True, quantity__gte=1).order_by('category', 'name')

    def __str__(self):
        return f'{self.name} | {self.category.name}'

products/views.py
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render, get_object_or_404

from baskets.models import Basket
from products.models import ProductCategory, Product
import random

from django.conf import settings
from django.core.cache import cache
from django.views.decorators.cache import cache_page, never_cache

def index(request):
    context = {'title': 'GeekShop'}
    return render(request, 'products/index.html', context)

def get_links_menu():
    if settings.LOW_CACHE:
        key = 'links_menu'
        links_menu = cache.get(key)
        if links_menu is None:
            links_menu = ProductCategory.objects.filter(is_active=True)
            cache.set(key, links_menu)
        return links_menu
    else:
        return ProductCategory.objects.filter(is_active=True)


def get_category(pk):
    if settings.LOW_CACHE:
        key = f'category_{pk}'
        category = cache.get(key)
        if category is None:
            category = get_object_or_404(ProductCategory, pk=pk)
            cache.set(key, category)
        return category
    else:
        return get_object_or_404(ProductCategory, pk=pk)


def get_products():
    if settings.LOW_CACHE:
        key = 'products'
        products = cache.get(key)
        if products is None:
            products = Product.objects.filter(is_active=True, category__is_active=True).select_related('category')
            cache.set(key, products)
        return products
    else:
        return Product.objects.filter(is_active=True, category__is_active=True).select_related('category')


def get_product(pk):
    if settings.LOW_CACHE:
        key = f'product_{pk}'
        product = cache.get(key)
        if product is None:
            product = get_object_or_404(Product, pk=pk)
            cache.set(key, product)
        return product
    else:
        return get_object_or_404(Product, pk=pk)


def get_products_orederd_by_price():
    if settings.LOW_CACHE:
        key = 'products_orederd_by_price'
        products = cache.get(key)
        if products is None:
            products = Product.objects.filter(is_active=True, category__is_active=True).order_by('price')
            cache.set(key, products)
        return products
    else:
        return Product.objects.filter(is_active=True, category__is_active=True).order_by('price')


def get_products_in_category_orederd_by_price(pk):
    if settings.LOW_CACHE:
        key = f'products_in_category_orederd_by_price_{pk}'
        products = cache.get(key)
        if products is None:
            products = Product.objects.filter(category__pk=pk, is_active=True, \
                                              category__is_active=True).order_by('price')
            cache.set(key, products)
        return products
    else:
        return Product.objects.filter(category__pk=pk, is_active=True, \
                                      category__is_active=True).order_by('price')


def get_basket(user):
    if user.is_authenticated:
        return Basket.objects.filter(user=user)
    else:
        return []


def get_hot_product():
    products = get_products()
    return random.sample(list(products), 1)[0]


def get_same_products(hot_product):
    same_products = Product.objects.filter(category=hot_product.category).exclude(pk=hot_product.pk)[:3]
    return same_products


@cache_page(3600)
def products(request, pk=None, page=1):
    title = 'Каталог'

    links_menu = get_links_menu()

    if pk is not None:
        if pk == 0:
            category = {'pk': 0, 'name': 'все'}
            products = get_products_orederd_by_price()
        else:
            category = get_category(pk)
            products = get_products_in_category_orederd_by_price(pk)

        paginator = Paginator(products, 3)
        try:
            products_paginator = paginator.page(page)
        except PageNotAnInteger:
            products_paginator = paginator.page(1)
        except EmptyPage:
            products_paginator = paginator.page(paginator.num_pages)

        context = {
            'title': title,
            'links_menu': links_menu,
            'category': category,
            'products': products_paginator,
        }
        return render(request, 'products/products.html', context)

    hot_product = get_hot_product()
    same_products = get_same_products(hot_product)
    products = get_products()[:3]

    context = {
        'title': title,
        'links_menu': links_menu,
        'hot_product': hot_product,
        'same_products': same_products,
        'products': products,
    }

    return render(request, 'products/products.html', context)


def product(request, pk):
    title = 'Детали'

    product = get_product(pk)

    context = {
        'title': title,
        'links_menu': get_links_menu(),
        'product': product,
        'same_products': get_same_products(product),
    }
    return render(request, 'products/product.html', context)

admins/templates/admins/admin-users-create.html
{% extends 'admins/base.html' %}

{% block content %}
    <main>
        <div class="container-fluid">
            <h1 class="mt-4">Создание пользователя</h1>
            <form action="{% url 'admins:admin_users_create' %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-row">
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label class="small mb-1" for="{{ form.first_name.id_for_label }}">Имя</label>
                            {{ form.first_name }}
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label class="small mb-1" for="{{ form.last_name.id_for_label }}">Фамилия</label>
                            {{ form.last_name }}
                        </div>
                    </div>
                </div>
                <div class="form-row mb-2">
                    <div class="col-lg-12">
                        <div class="custom-file">
                            {{ form.avatar }}
                            <label class="custom-file-label" for="{{ form.avatar.id_for_label }}">Выберите
                                изображение</label>
                        </div>
                    </div>
                </div>
                <div class="form-row">
                    <div class="col-lg-6">
                        <label class="small mb-1" for="{{ form.username.id_for_label }}">Имя пользователя</label>
                        {{ form.username }}
                    </div>
                    <div class="col-lg-6">
                        <label class="small mb-1" for="{{ form.email.id_for_label }}">Адрес электронной
                            почты</label>
                        {{ form.email }}
                    </div>
                </div>
                <div class="form-row">
                    <div class="col-lg-6">
                        <label class="small mb-1" for="{{ form.password1.id_for_label }}">Пароль</label>
                        {{ form.password1 }}
                    </div>
                    <div class="col-lg-6">
                        <label class="small mb-1" for="{{ form.password2.id_for_label }}">Повторите пароль</label>
                        {{ form.password2 }}
                    </div>
                </div>
                <div class="form-row">
                    <div class="col-lg-12" style="margin-top: 33px;">
                        <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                    </div>
                </div>
            </form>
        </div>
    </main>
{% endblock %}

admins/templates/admins/admin-users-read.html
{% extends 'admins/base.html' %}

{% block content %}
    <main>
        <div class="container-fluid">
            <h1 class="mt-4">Пользователи</h1>
            <div class="card mb-4">
                <div class="card-header">
                    <i class="fas fa-table mr-1"></i>
                    Пользователи
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                            <thead>
                            <tr>
                                <th>Имя пользователя</th>
                                <th>Имя</th>
                                <th>Фамилия</th>
                                <th>Адрес эл. почты</th>
                                <th>Персонал сайта</th>
                                <th>Активный</th>
                            </tr>
                            </thead>
                            <tfoot>
                            <tr>
                                <th>Имя пользователя</th>
                                <th>Имя</th>
                                <th>Фамилия</th>
                                <th>Адрес эл. почты</th>
                                <th>Персонал сайта</th>
                                <th>Активный</th>
                            </tr>
                            </tfoot>
                            <tbody>
                            {% for user in object_list %}
                                <tr>
                                    <td><a href="{% url 'admins:admin_users_update' user.id %}" style="color: dodgerblue">{{ user.username }}</a></td>
                                    <td>{{ user.first_name }}</td>
                                    <td>{{ user.last_name }}</td>
                                    <td>{{ user.email }}</td>
                                    <td class="text-center">
                                        {% if user.is_staff %}
                                            <i class="fas fa-check-circle"></i>
                                        {% else %}
                                            <i class="fas fa-times-circle"></i>
                                        {% endif %}
                                    </td>
                                    <td class="text-center">
                                        {% if user.is_active %}
                                            <i class="fas fa-check-circle"></i>
                                        {% else %}
                                            <i class="fas fa-times-circle"></i>
                                        {% endif %}
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="card-footer">
                    <a href="{% url 'admins:admin_users_create' %}">
                        <button class="btn btn-success">Создать пользователя</button>
                    </a>
                </div>
            </div>
        </div>
    </main>
{% endblock %}

admins/templates/admins/admin-users-update-delete.html
{% extends 'admins/base.html' %}

{% block content %}
    <h1 class="mt-4">Редактирование пользователя | {{ user.username }}</h1>
    <div class="card-body">
        <form action="{% url 'admins:admin_users_update' user.id %}" method="post"
              enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-row">
                <div class="col-lg-6">
                    <div class="form-group">
                        <label class="small mb-1" for="{{ form.first_name.id_for_label }}">Имя</label>
                        {{ form.first_name }}
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="form-group">
                        <label class="small mb-1" for="{{ form.last_name.id_for_label }}">Фамилия</label>
                        {{ form.last_name }}
                    </div>
                </div>
            </div>
            <div class="form-row mb-2">
                <div class="col-lg-12">
                    <div class="custom-file">
                        {{ form.avatar }}
                        <label class="custom-file-label" for="{{ form.avatar.id_for_label }}">Выберите
                            изображение</label>
                    </div>
                </div>
            </div>
            <div class="form-row">
                <div class="col-lg-6">
                    <label class="small mb-1" for="{{ form.username.id_for_label }}">Имя пользователя</label>
                    {{ form.username }}
                </div>
                <div class="col-lg-6">
                    <label class="small mb-1" for="{{ form.email.id_for_label }}">Адрес электронной
                        почты</label>
                    {{ form.email }}
                </div>
            </div>
            <div class="form-row">
                <div class="col-lg-12" style="margin-top: 33px;">
                    <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                </div>
            </div>
        </form>
        <div class="row">
            <div class="col-lg-12" style="margin-top: 33px;">
                <a href="{% url 'admins:admin_users_remove' user.id %}">
                    <form action="{% url 'admins:admin_users_remove' user.id %}" method="post">
                    {% csrf_token %}
                    <input class="btn btn-danger btn-block" type="submit" value="Удалить">
                </a>
            </div>
        </div>
    </div>
{% endblock %}

admins/templates/admins/base.html
py{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>{{ title }}</title>
    <link href="{% static 'css/auth-admin.css' %}" rel="stylesheet"/>
    <link href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css" rel="stylesheet"
          crossorigin="anonymous"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/js/all.min.js"
            crossorigin="anonymous"></script>
</head>
<body class="sb-nav-fixed">
<nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'admins:index' %}">GeekShop</a>
    <button class="btn btn-link btn-sm order-1 order-lg-0" id="sidebarToggle" href="#"><i class="fas fa-bars"></i>
    </button>
    <!-- Navbar Search-->
    <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
        <div class="input-group">
            <input class="form-control" type="text" placeholder="Поиск..." aria-label="Search"
                   aria-describedby="basic-addon2"/>
            <div class="input-group-append">
                <button class="btn btn-primary" type="button"><i class="fas fa-search"></i></button>
            </div>
        </div>
    </form>
    <!-- Navbar-->
    <ul class="navbar-nav ml-auto ml-md-0">
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" id="userDropdown" href="#" role="button" data-toggle="dropdown"
               aria-haspopup="true" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                <a class="dropdown-item" href="{% url 'users:logout' %}">Logout</a>
            </div>
        </li>
    </ul>
</nav>
<div id="layoutSidenav">
    <div id="layoutSidenav_nav">
        <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
            <div class="sb-sidenav-menu">
                <div class="nav">
                    <div class="sb-sidenav-menu-heading">Приложения</div>
                    <a class="nav-link" href="{% url 'admins:admin_users' %}">
                        <div class="sb-nav-link-icon">
                            <i class="fas fa-users"></i>
                        </div>
                        Пользователи
                    </a>
                    <a class="nav-link" href="{% url 'admins:categories' %}">
                        <div class="sb-nav-link-icon">
                            <i class="fas fa-shopping-basket"></i>
                        </div>
                        Категории
                    </a>
                    <a class="nav-link" href="{% url 'admins:products' %}">
                        <div class="sb-nav-link-icon">
                            <i class="fas fa-tshirt"></i>
                        </div>
                        Продукты
                    </a>
                </div>
            </div>
            <div class="sb-sidenav-footer"></div>
        </nav>
    </div>
    <div id="layoutSidenav_content">
        {% block content %} {% endblock %}
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid">
                <div class="d-flex align-items-center justify-content-between small">
                    <div class="text-muted">Copyright &copy; GeekShop 2021</div>
                </div>
            </div>
        </footer>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        crossorigin="anonymous"></script>
<script src="{% static 'js/auth-admin.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js" crossorigin="anonymous"></script>
<script src="{% static 'js/datatable.js' %}"></script>
</body>
</html>

admins/templates/admins/categories.html
{% extends 'admins/base.html' %}
{% load static %}

{% block content %}
<main>
    <div class="container-fluid">
        <h1 class="mt-4">Категории товаров</h1>
        <div class="card mb-4">
            <div class="card-header">
                <i class="fas fa-table mr-1"></i>
                Категории
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                        <tr>
                            <th>Наименование</th>
                            <th>Товары</th>
                            <th>Редактировать</th>
                            <th>Удалить</th>
                        </tr>
                        </thead>
                        <tfoot>
                        <tr>
                            <th>Наименование</th>
                            <th>Товары</th>
                            <th>Редактировать</th>
                            <th>Удалить</th>
                        </tr>
                        </tfoot>
                        <tbody>
                        {% for category in objects %}
                            <tr {% if not category.is_active %} style="opacity: 0.5;" {% endif %}>
                                <td>{{ category.name }}</td>
                                <td><a href="{% url 'admins:products'%}">Товары</a></td>
                                <td class="text-center">
                                    <a href="{% url 'admins:category_update' category.pk %}">Edit</a>
                                </td>
                                <td>
                                    <a {% if not category.is_active %} class="invisible" {% endif %} href="{#% url 'admins:product_delete' pk=product.id %#}">
                                        <i class="fa fa-times-circle"></i>
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="card-footer">
{#                <a href="{% url 'admins:product_create' category.pk %}">#}
                    <button class="btn btn-success">Создать категорию</button>
                </a>
            </div>
        </div>
    </div>
</main>
{% endblock %}

admins/templates/admins/index.html
{% extends 'admins/base.html' %}

{% block content %}
    <main>
        <div class="container-fluid">
            <h1 class="mt-4">Административная панель</h1>
        </div>
    </main>
{% endblock %}

admins/templates/admins/products.html
{% extends 'admins/base.html' %}
{% load static %}

{% block content %}
<main>
    <div class="container-fluid">
        <h1 class="mt-4">Товары</h1>
        <div class="card mb-4">
            <div class="card-header">
                <i class="fas fa-table mr-1"></i>
                Товары
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                        <tr>
                            <th>Наименование</th>
                            <th>Количество</th>
                            <th>Стоимость</th>
                            <th>Детали</th>
                            <th>Редактировать</th>
                            <th>Удалить</th>
                        </tr>
                        </thead>
                        <tfoot>
                        <tr>
                            <th>Наименование</th>
                            <th>Количество</th>
                            <th>Стоимость</th>
                            <th>Детали</th>
                            <th>Редактировать</th>
                            <th>Удалить</th>
                        </tr>
                        </tfoot>
                        <tbody>
                        {% for product in objects %}
                            <tr {% if not product.is_active %} style="opacity: 0.5;" {% endif %}>
                                <td>{{ product.name }}</td>
                                <td>{{ product.quantity }}</td>
                                <td>{{ product.price }}</td>
                                <td class="text-center">
                                    <a href="{% url 'admins:product_read' product.pk %}">Detail</a>
                                </td>
                                <td class="text-center">
                                    <a href="{% url 'admins:product_update' product.pk %}">Edit</a>
                                </td>
                                <td>
                                    <a {% if not product.is_active %} class="invisible" {% endif %} href="{% url 'admins:product_delete' pk=product.id %}">
                                        <i class="fa fa-times-circle"></i>
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>

        </div>
    </div>
</main>
{% endblock %}